In [1]:
import pandas as pd

In [2]:
application=pd.read_csv("Dataset/application_record.csv")
credit=pd.read_csv("Dataset/credit_record.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Dataset/application_record.csv'

In [3]:
import pandas as pd

application = pd.read_csv("Dataset/application_record.csv")
credit = pd.read_csv("Dataset/credit_record.csv")

In [4]:
application.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1

In [5]:
credit.head()

  ID,MONTHS_BALANCE,STATUS
0              5001711,0,X
1             5001711,-1,0
2             5001711,-2,0
3             5001711,-3,0
4              5001712,0,C

In [6]:
applications.columns

NameError: name 'applications' is not defined

In [7]:
application.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS'],
      dtype='object')

In [8]:
credit.columns

Index(['ID,MONTHS_BALANCE,STATUS'], dtype='object')

In [9]:
status_map = {
    'C': 1,
    'X': 1,
    '0': 1,
    '1': 0,
    '2': 0,
    '3': 0,
    '4': 0,
    '5': 0
}

credit['TARGET'] = credit['STATUS'].map(status_map)

KeyError: 'STATUS'

In [10]:
credit = pd.read_csv("Dataset/credit_record.csv", sep=",")

In [11]:
credit.columns

Index(['ID,MONTHS_BALANCE,STATUS'], dtype='object')

In [12]:
credit.head(3)

  ID,MONTHS_BALANCE,STATUS
0              5001711,0,X
1             5001711,-1,0
2             5001711,-2,0

In [13]:
with open("Dataset/credit_record.csv", "r") as f:
    for i in range(5):
        print(repr(f.readline()))

'ï»¿"ID,MONTHS_BALANCE,STATUS"\n'
'"5001711,0,X"\n'
'"5001711,-1,0"\n'
'"5001711,-2,0"\n'
'"5001711,-3,0"\n'

In [14]:
credit = pd.read_csv("Dataset/credit_record.csv", encoding="utf-8-sig")

In [15]:
print(credit.columns)

Index(['ID,MONTHS_BALANCE,STATUS'], dtype='object')

In [16]:
credit = pd.read_csv(
    "Dataset/credit_record.csv",
    sep=",",
    encoding="utf-8-sig",
    engine="python"
)

print(credit.columns)
credit.head()

Index(['ID,MONTHS_BALANCE,STATUS'], dtype='object')

  ID,MONTHS_BALANCE,STATUS
0              5001711,0,X
1             5001711,-1,0
2             5001711,-2,0
3             5001711,-3,0
4              5001712,0,C

In [17]:
credit.shape

(1048575, 1)

In [18]:
import pandas as pd

credit = pd.read_csv(
    "Dataset/credit_record.csv",
    header=None,
    names=["raw"]
)

credit = credit["raw"].str.replace('"', "", regex=False).str.split(",", expand=True)
credit.columns = ["ID", "MONTHS_BALANCE", "STATUS"]

credit.head()

        ID  MONTHS_BALANCE  STATUS
0       ID  MONTHS_BALANCE  STATUS
1  5001711               0       X
2  5001711              -1       0
3  5001711              -2       0
4  5001711              -3       0

In [19]:
credit.columns

Index(['ID', 'MONTHS_BALANCE', 'STATUS'], dtype='object')

In [20]:
credit["ID"] = credit["ID"].astype("int64")
credit["MONTHS_BALANCE"] = credit["MONTHS_BALANCE"].astype("int64")

ValueError: invalid literal for int() with base 10: 'ID'

In [21]:
credit.head()

        ID  MONTHS_BALANCE  STATUS
0       ID  MONTHS_BALANCE  STATUS
1  5001711               0       X
2  5001711              -1       0
3  5001711              -2       0
4  5001711              -3       0

In [22]:
credit = credit.iloc[1:].reset_index(drop=True)

In [23]:
credit["ID"] = credit["ID"].astype("int64")
credit["MONTHS_BALANCE"] = credit["MONTHS_BALANCE"].astype("int64")

In [24]:
credit.head()
credit.dtypes

ID                 int64
MONTHS_BALANCE     int64
STATUS            object
dtype: object

In [25]:
status_map = {
    'C': 1,
    'X': 1,
    '0': 0,
    '1': 1,
    '2': 1,
    '3': 1,
    '4': 1,
    '5': 1
}

credit["TARGET"] = credit["STATUS"].map(status_map)

In [26]:
credit.head()

        ID  MONTHS_BALANCE STATUS  TARGET
0  5001711               0      X       1
1  5001711              -1      0       0
2  5001711              -2      0       0
3  5001711              -3      0       0
4  5001712               0      C       1

In [27]:
credit_target = credit.groupby("ID")["TARGET"].max().reset_index()

In [28]:
credit_target.head()

        ID  TARGET
0  5001711       1
1  5001712       1
2  5001713       1
3  5001714       1
4  5001715       1

In [29]:
data = application.merge(credit_target, on="ID", how="inner")

In [30]:
data.head()
data.shape

(36457, 19)

In [31]:
data.isnull().sum()

ID                         0
CODE_GENDER                0
FLAG_OWN_CAR               0
FLAG_OWN_REALTY            0
CNT_CHILDREN               0
AMT_INCOME_TOTAL           0
NAME_INCOME_TYPE           0
NAME_EDUCATION_TYPE        0
NAME_FAMILY_STATUS         0
NAME_HOUSING_TYPE          0
DAYS_BIRTH                 0
DAYS_EMPLOYED              0
FLAG_MOBIL                 0
FLAG_WORK_PHONE            0
FLAG_PHONE                 0
FLAG_EMAIL                 0
OCCUPATION_TYPE        11323
CNT_FAM_MEMBERS            0
TARGET                     0
dtype: int64

In [32]:
data = data.drop_duplicates()

In [33]:
data["AGE"] = (-data["DAYS_BIRTH"] / 365).astype(int)

In [34]:
import numpy as np

data["DAYS_EMPLOYED"] = data["DAYS_EMPLOYED"].replace(365243, np.nan)
data["YEARS_EMPLOYED"] = (-data["DAYS_EMPLOYED"] / 365)

In [35]:
data.drop(columns=["DAYS_BIRTH", "DAYS_EMPLOYED"], inplace=True)

In [36]:
binary_cols = [
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY"
]

for col in binary_cols:
    print(col, data[col].unique())

CODE_GENDER ['M' 'F']
FLAG_OWN_CAR ['Y' 'N']
FLAG_OWN_REALTY ['Y' 'N']

In [37]:
data["OCCUPATION_TYPE"] = data["OCCUPATION_TYPE"].fillna("Unknown")
data["YEARS_EMPLOYED"] = data["YEARS_EMPLOYED"].fillna(data["YEARS_EMPLOYED"].median())

In [38]:
data["CODE_GENDER"] = data["CODE_GENDER"].map({"M": 1, "F": 0})
data["FLAG_OWN_CAR"] = data["FLAG_OWN_CAR"].map({"Y": 1, "N": 0})
data["FLAG_OWN_REALTY"] = data["FLAG_OWN_REALTY"].map({"Y": 1, "N": 0})

In [39]:
categorical_cols = [
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "OCCUPATION_TYPE"
]

data = pd.get_dummies(
    data,
    columns=categorical_cols,
    drop_first=True
)

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 49 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   ID                                                 36457 non-null  int64
 1   CODE_GENDER                                        36457 non-null  int64
 2   FLAG_OWN_CAR                                       36457 non-null  int64
 3   FLAG_OWN_REALTY                                    36457 non-null  int64
 4   CNT_CHILDREN                                       36457 non-null  int64
 5   AMT_INCOME_TOTAL                                   36457 non-null  float64
 6   FLAG_MOBIL                                         36457 non-null  int64
 7   FLAG_WORK_PHONE                                    36457 non-null  int64
 8   FLAG_PHONE                                         36457 non-null  int64
 9   FLAG_EMAIL                                         36457 non-null  int64
 10  CNT_FAM_MEMBERS                                    36457 non-null  int64
 11  TARGET                                             36457 non-null  int64
 12  AGE                                                36457 non-null  int64
 13  YEARS_EMPLOYED                                     36457 non-null  float64
 14  NAME_INCOME_TYPE_Pensioner                         36457 non-null  bool
 15  NAME_INCOME_TYPE_State servant                     36457 non-null  bool
 16  NAME_INCOME_TYPE_Student                           36457 non-null  bool
 17  NAME_INCOME_TYPE_Working                           36457 non-null  bool
 18  NAME_EDUCATION_TYPE_Higher education               36457 non-null  bool
 19  NAME_EDUCATION_TYPE_Incomplete higher              36457 non-null  bool
 20  NAME_EDUCATION_TYPE_Lower secondary                36457 non-null  bool
 21  NAME_EDUCATION_TYPE_Secondary / secondary special  36457 non-null  bool
 22  NAME_FAMILY_STATUS_Married                         36457 non-null  bool
 23  NAME_FAMILY_STATUS_Separated                       36457 non-null  bool
 24  NAME_FAMILY_STATUS_Single / not married            36457 non-null  bool
 25  NAME_FAMILY_STATUS_Widow                           36457 non-null  bool
 26  NAME_HOUSING_TYPE_House / apartment                36457 non-null  bool
 27  NAME_HOUSING_TYPE_Municipal apartment              36457 non-null  bool
 28  NAME_HOUSING_TYPE_Office apartment                 36457 non-null  bool
 29  NAME_HOUSING_TYPE_Rented apartment                 36457 non-null  bool
 30  NAME_HOUSING_TYPE_With parents                     36457 non-null  bool
 31  OCCUPATION_TYPE_Cleaning staff                     36457 non-null  bool
 32  OCCUPATION_TYPE_Cooking staff                      36457 non-null  bool
 33  OCCUPATION_TYPE_Core staff                         36457 non-null  bool
 34  OCCUPATION_TYPE_Drivers                            36457 non-null  bool
 35  OCCUPATION_TYPE_HR staff                           36457 non-null  bool
 36  OCCUPATION_TYPE_High skill tech staff              36457 non-null  bool
 37  OCCUPATION_TYPE_IT staff                           36457 non-null  bool
 38  OCCUPATION_TYPE_Laborers                           36457 non-null  bool
 39  OCCUPATION_TYPE_Low-skill Laborers                 36457 non-null  bool
 40  OCCUPATION_TYPE_Managers                           36457 non-null  bool
 41  OCCUPATION_TYPE_Medicine staff                     36457 non-null  bool
 42  OCCUPATION_TYPE_Private service staff              36457 non-null  bool
 43  OCCUPATION_TYPE_Realty agents                      36457 non-null  bool
 44  OCCUPATION_TYPE_Sales staff                        36457 non-null  bool
 45  OCCUPATION_TYPE_Secretaries                        36457 non-null  bool
 46  OCCUPATION_TYPE_Security staff                     36457 non-null  bool
 47  OCCUPATION_TYPE_Unknown                            36457 non-null  bool
 48  OCCUPATION_TYPE_Waiters/barmen staff               36457 non-null  bool
dtypes: bool(35), float64(2), int64(12)
memory usage: 5.1 MB

In [41]:
data.to_csv("Dataset/feature_engineered_data.csv", index=False)

In [42]:
data.head()
data.shape

(36457, 49)

In [43]:
data.to_csv("Dataset/feature_engineered_data.csv", index=False)